# Generated by Django 2.0.3 on 2018-03-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='专辑名')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chindren', to='album.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='歌曲名')),
                ('albums', models.ManyToManyField(related_name='musics', to='album.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='categories',
            field=models.ManyToManyField(to='album.Category'),
        ),
    ]
