# Generated by Django 2.0.3 on 2018-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180328_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='musics', to='album.Album'),
        ),
    ]
